-[] State shape for Leads byBounty: https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape#designing-a-normalized-state
    -[] Clicking a bounty emits event.Change active state.
- [] Leads listen to CLICK_BOUNTY
    - [] On click, set active bounty and switch leads per bounty
        - [] Add lead to Leads byBounty state